### PR TITLE
Optional is now Dart 2.x ready

### PR DESCRIPTION
**Pull request by MikeMitterer**
Hi, works with Dart 2.x

Here is what I did before I created this PR
```bash
dartanalyzer lib
dartanalyzer test/
pub run build_runner test -- -p chrome
pub run build_runner test
```
I

### CODE REVIEW

**Comment by MikeMitterer** [comment]
It would be cool if you could release a new version of optional on pub ASAP because I'm using it in some of my packages.
Thanks in advance
Mike

**Comment by tonio-ramirez** [comment]
Wow, I didn't know anybody was actually using this; that's good to know.  I noticed you removed some methods/operators, removed some/most of the use of the EMPTY constant, and removed some tests.  Care to discuss the reasoning behind that?

I'm a bit reluctant to merge a pull request that removes both functionality and tests without more explanation, but bear in mind you can always fork the repo and publish (and use) your own version. =)

**Comment by tonio-ramirez** [comment]
Investigated a bit, changed some dependencies, and fixed up the code.

Published version 2.0.0 which is Dart 2 compatible.

**Comment by MikeMitterer** [comment]
Thanks for publishing the repo!
I removed some functions because I thought they were not relevant and I needed a D2-Version as quick a possible.
Thanks for your investigation.

**Pull request closed without merging**
